# -*- mode: ruby -*-
# vi: set ft=ruby :

### Configuration
nodes_config = (JSON.parse(File.read("config/nodes.json")))['nodes']
control_repo = ENV['CONTROL_REPO'] || "../puppet/control"

### Vagrant

Vagrant.configure("2") do |config|

  nodes_config.each do |node|
    node_name   = node[0] # name of node
    node_values = node[1] # content of node

    config.vm.define node_name do |config|
      # Configure node hostname
      config.vm.host_name = "%s" % node_name

      # Configure base box
      config.vm.box_url = 'https://vagrantcloud.com/puppetlabs/boxes/centos-7.2-64-puppet'
      config.vm.box = node_values[':base']

      # Configure memory and cpus
      config.vm.provider 'virtualbox' do |vb|
        vb.name = node_name
        vb.customize ['modifyvm', :id, '--memory', node_values[':memory']] if node_values[':memory']
        vb.customize ['modifyvm', :id, '--cpus', node_values[':cpus']] if node_values[':cpus']
        vb.customize ['modifyvm', :id, '--cpuexecutioncap', node_values[':cpuexecutioncap']] if node_values[':cpuexecutioncap']
        vb.customize ['modifyvm', :id, "--hostonlyadapter2", "vboxnet0"]
      end

      # Configure forwarding ports
      ports = node_values['ports']
      ports.each do |port|
        config.vm.network :forwarded_port,
          host:  port[':host'],
          guest: port[':guest'],
          id:    port[':id']
      end

      # Configure ip address
      if node_values[':ip'] == 'dhcp'
        config.vm.network "private_network", type: "dhcp", auto_config: true
      else
        config.vm.network "private_network", ip: node_values[':ip']
      end

      # Run scripts from node configuration
      if node_values['scripts']
        node_values['scripts'].each do |script|
          config.vm.provision :shell, :inline => script
        end
      end

      # Synchronise control into the masterless environment on the node
      config.vm.synced_folder "#{control_repo}", "/etc/puppetlabs/code/environments/masterless"

      if node_values['modules']
        node_values['modules'].each do |mod|
          config.vm.synced_folder "../puppet/modules/#{mod}", "/etc/puppetlabs/code/environments/masterless/modules/#{mod}"
        end
      end

      # Invokes puppet provisioner
      config.vm.provision "puppet" do |puppet|
        puppet.environment_path = ["vm", "/etc/puppetlabs/code/environments"]
        puppet.environment = "masterless"
            puppet.facter = { "role" => node_name }
        puppet.hiera_config_path = "#{control_repo}/hiera.yaml"
        puppet.options = "--verbose --environment masterless"
      end

      # Module testing
      node_values['modules'].each do |mod|
        config.vm.provision :shell, :inline => "puppet parser validate ."
        config.vm.provision :shell, :inline => "puppet-lint ."
        config.vm.provision :shell, :inline => "cd /etc/puppetlabs/code/environments/masterless/modules/#{mod} && /opt/puppetlabs/puppet/bin/rake spec"
      end

    end

  end

end
